### ISSUE TITLE
Does the old method using a middle pc still work?

### ISSUE THREAD

**Issue by toolsofpwnage** [FutureXpo/PUBG-RADAR-8K#1]
in the title

**Comment by 1072537350** [comment]
no still work

**Comment by toolsofpwnage** [comment]
@1072537350 Sorry just to confirm. Do you mean "yes the radar can be successfully used via a middle pc", or "no the radar can not be used that way"? Your answer is a bit confusing

**Comment by 1072537350** [comment]
no the radar can not be used

**Comment by toolsofpwnage** [comment]
@1072537350 thanks

**Comment by FutureXpo** [comment]
Now can be used(after last update)
