### ISSUE TITLE
Problem with starting radar

### ISSUE THREAD

**Issue by Flaave** [FutureXpo/PUBG-RADAR-8K#3]
Exception in thread "main" java.lang.ExceptionInInitializerError
        at pubg.radar.GameKt.main(Game.kt:56)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at pubg.radar.sniffer.Sniffer.<clinit>(Sniffer.kt:200)
        ... 1 more

Can't open radar, help pls.

**Comment by Dolajzis** [comment]
same problem here

**Comment by Jeziu** [comment]
use driver booster 5.2 pro (find serial by google and activate it without internet connection) to download all game drivers like vc++

**Comment by Dolajzis** [comment]
will try, thanks

**Comment by Flaave** [comment]
Yep, it helps me too. If u're starting radar from 2nd PC with VPN methon in instruction and place your main IP adress (not VPN ip) instead of "%_IPaddr%". Or make a new bat file: 
java -jar pubg-radar-1.0-SNAPSHOT-jar-with-dependencies.jar "111" PortFilter "222"
Where:
111 - it's your main IP adress
222 - your game pc IP of VPN connection (not your main IP adress)

P.S. Sry for my bad English guys))
