### ISSUE TITLE
Menu not show actual key bindings

### ISSUE THREAD

**Issue by bhairawa** [FutureXpo/PUBG-RADAR-8K#4]
Hello, i rebind default keys, cause i dont have NUMPAD on my laptop. But on-map menu still show default keys(NUMPAD1-9, etc). This a not big deal, just it will be nice if it fixed )
Thanx!

**Comment by FutureXpo** [comment]
it's a solid picture, and I'm not going to change it. If you want to change this, use the paint / photoshop

**Comment by bhairawa** [comment]
Anyway thank you, your radar is best.
