### ISSUE TITLE
Doesn't work with Gun Skins Update + Discord is down

### ISSUE THREAD

**Issue by CodeF53** [FutureXpo/PUBG-RADAR-8K#5]
Stopped working after the gun skins update dropped.
After launching arpspoof.bat, AUTOON.bat, and putting my ip in them on a Virtual Machine the display stays grey when entering a match.

**Comment by lu03797** [comment]
Blue holes are encrypted and can't be used for the time being

**Comment by FutureXpo** [comment]
Yeah, now players are trying to crack this encryption, but now its not working
