### ISSUE TITLE
radar no show~ CMD MESSAGE.

### ISSUE THREAD

**Issue by the7thway** [FutureXpo/PUBG-RADAR-8K#9]
reinstalled my system and somehow this showed up~, java, wincap. maven all installed, 
![qq 20180310172419](https://user-images.githubusercontent.com/37020367/37248469-fa5deef0-2487-11e8-9823-2472b4db2f5a.png)

**Comment by DMKISSMYASS** [comment]
Test server ?

**Comment by the7thway** [comment]
no. its public server, before i reinstall my window system it works fine. WIN7 X64. before and after.

**Comment by DMKISSMYASS** [comment]
Ah i have the same error on test server ...

**Comment by the7thway** [comment]
did the radar work for you before? before i reinstall my windows system, never had any problem running it~ i run is on game pc while using hidetools to hide jar so BE wont find out....still not banned.

**Comment by DMKISSMYASS** [comment]
You use the radar on a 2nd pc or on your pc gaming or a Vmware?

**Comment by the7thway** [comment]
on gaming pc with 2nd monitor, no VM. just use hidetool to hide java.exe from windows task manager, so BE cant detected it. pubg wont allow vm to run.. will show 25 VM not allowed.

**Comment by FutureXpo** [comment]
If you have problems with 1.0.7 version, use 1.0.6 or [original version](https://github.com/AiYinZiLeGong/PUBG-Radar), becose i have no problems with it
